services:
  nginx:
    container_name: TennisScoreBoard_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - php
      - db
  php:
    container_name: TennisScoreBoard_php
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
    - ./:/var/www/
    depends_on:
      - db
  db:
    container_name: TennisScoreBoard_db
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root