services:
  nginx:
    container_name: TennisScoreBoard_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - php
      - database
  php:
    container_name: TennisScoreBoard_php
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
  database:
    container_name: TennisScoreBoard_database
    image: postgres:12
    volumes:
      - ./_docker/Database/init.sql:/docker-entrypoint-initdb.d/Database.sql
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
    ports:
      - "5432:5432"