services:
  nginx:
    container_name: TennisScoreBoard_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - php
      - database
  php:
    container_name: TennisScoreBoard_php
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
      - database
  database:
    container_name: TennisScoreBoard_database
    image: postgres:12
    volumes:
      - ./_docker/init/Database_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
    ports:
      - "5432:5432"